# Generated by Django 5.1.1 on 2024-10-13 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('family', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)])),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('CB', 'Center-back'), ('LB', 'Left-back'), ('RB', 'Right-back'), ('CM', 'Central Midfielder'), ('CDM', 'Defensive Midfielder'), ('CAM', 'Attacking Midfielder'), ('ST', 'Striker'), ('LW', 'Left Winger'), ('RW', 'Right Winger')], max_length=3)),
                ('img', models.ImageField(blank=True, upload_to='players/images')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
